# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c30fec64dfa9ed2c072be79fa5fb37d986897e7d00102501be3930fdaaa5bd99c25361422637b2d9dac2020bd5c31dba0c34de6f81e18e0db84738b88a8a8a7d

test:
  secret_key_base: a3b795928fcb0a517f7287321cf6cfff20673a87a75650531152131e530216f7fcc14bacf638ad05b53d85054e1ab43dbdcfbf81feea76c3ce485678fe1343d6

staging:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
